# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_data', models.CharField(max_length=30)),
                ('isWrite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='apiName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='apiProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('doc_path', models.CharField(max_length=30)),
                ('descripts', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='apiname',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTests.apiProject'),
        ),
        migrations.AddField(
            model_name='apidata',
            name='apiName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTests.apiName'),
        ),
    ]
