# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTests', '0003_auto_20160607_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproject',
            name='descripts',
            field=models.CharField(max_length=100),
        ),
    ]
