# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTests', '0004_auto_20160607_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiname',
            name='post_url',
            field=models.CharField(default='', max_length=30),
        ),
    ]
