# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTests', '0007_apidata_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='test',
        ),
    ]
