# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTests', '0009_auto_20160608_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='isSystem',
        ),
    ]
