# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTests', '0010_remove_apidata_issystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='dataName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
